In [69]:
import pandas as pd
import numpy as np
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer 
from sklearn.feature_extraction.text import TfidfVectorizer
from IPython.display import HTML
from pivottablejs import pivot_ui
import tensorflow as tf
from tensorflow import keras
%config IPCompleter.greedy=True

ModuleNotFoundError: No module named 'tensorflow'

In [17]:
df = pd.read_csv("tsv/train.tsv", sep='\t')
df.head()

In [63]:
newDFArray = []
ps= PorterStemmer()
tokenizer = RegexpTokenizer(r'\w+')
lemmatizer = WordNetLemmatizer()
prevsentence = np.zeros([0])
for index,row in df.iterrows():
    newsentence = []
    sentence = tokenizer.tokenize(row["Phrase"])
    for word in sentence:
        word = word.lower()
        word = lemmatizer.lemmatize(word)
        word = ps.stem(word)
        if (word not in stopwords.words('english')):
            newsentence.append(word)
            
    #caters for first row        
    if len(prevsentence) == 0:
        if len(newsentence) > 0:
            prevsentence = [row["SentenceId"], newsentence, row["Sentiment"]]
            continue
            
    if row["SentenceId"] == prevsentence[0]:
            if len(newsentence) > len(prevsentence[1]):
                prevsentence = [row["SentenceId"], newsentence, row["Sentiment"]]
    else:
            newDFArray.append(prevsentence)
            prevsentence = [row["SentenceId"], newsentence, row["Sentiment"]]

In [64]:
newDF = pd.DataFrame(newDFArray, columns=['SentenceId','Phrase', 'Sentiment'] )
newDF.describe()

        SentenceId    Sentiment
count  8528.000000  8528.000000
mean   4269.182223     2.062735
std    2466.415865     1.277469
min       1.000000     0.000000
25%    2132.750000     1.000000
50%    4267.500000     2.000000
75%    6405.250000     3.000000
max    8543.000000     4.000000

In [65]:
newDF.head()

   SentenceId                                             Phrase  Sentiment
0           1  [seri, escapad, demonstr, adag, good, goos, al...          1
1           2  [thi, quiet, introspect, entertain, independ, ...          4
2           3  [even, fan, ismail, merchant, work, suspect, w...          1
3           4  [posit, thrill, combin, ethnographi, intrigu, ...          3
4           5        [aggress, self, glorif, manipul, whitewash]          1

In [66]:
df.describe()

            PhraseId     SentenceId      Sentiment
count  156060.000000  156060.000000  156060.000000
mean    78030.500000    4079.732744       2.063578
std     45050.785842    2502.764394       0.893832
min         1.000000       1.000000       0.000000
25%     39015.750000    1861.750000       2.000000
50%     78030.500000    4017.000000       2.000000
75%    117045.250000    6244.000000       3.000000
max    156060.000000    8544.000000       4.000000

In [67]:
newDF.to_csv('export_dataframe.csv', index = False, header=True)

In [68]:
model = keras.Sequential()
model.add(
  keras.layers.Dense(
    units=256,
    input_shape=(X_train.shape[1], ),
    activation='relu'
  )
)
model.add(
  keras.layers.Dropout(rate=0.5)
)
model.add(
  keras.layers.Dense(
    units=128,
    activation='relu'
  )
)
model.add(
  keras.layers.Dropout(rate=0.5)
)
model.add(keras.layers.Dense(2, activation='softmax'))
model.compile(
    loss='categorical_crossentropy',
    optimizer=keras.optimizers.Adam(0.001),
    metrics=['accuracy']
)

NameError: name 'keras' is not defined